# 1. Ethereum
[mainnet]
endpoint_url = "mainnet-rpc-url"

[mainnet.string]
dappKey_c3gov_u = "v1.continuumdao.c3governor_u"
dappKey_ctm = "v1.continuumdao.ctm"

[mainnet.address]
admin = "0xccc435AaBc481D4Af9da51E51Eb2a383Bce6791F"


# 2. Linea
[linea]
endpoint_url ="linea-rpc-url"

[linea.string]
dappKey_c3gov_u = "v1.continuumdao.c3governor_u"
dappKey_ctm = "v1.continuumdao.ctm"

[linea.address]
admin = "0xccc435AaBc481D4Af9da51E51Eb2a383Bce6791F"


# # 3. Sepolia
# [sepolia]
# endpoint_url = "sepolia-rpc-url"
# 
# [sepolia.string]
# dappKey_c3gov_u = "v1.continuumdao.c3governor_u"
# dappKey_ctm = "v1.continuumdao.ctm"
# 
# [sepolia.address]
# admin = "0xccc435AaBc481D4Af9da51E51Eb2a383Bce6791F"
# 
# 
# # 4. Linea Sepolia
# [linea-sepolia]
# endpoint_url = "linea-sepolia-rpc-url"
# 
# [linea-sepolia.string]
# dappKey_c3gov_u = "v1.continuumdao.c3governor_u"
# dappKey_ctm = "v1.continuumdao.ctm"
# 
# [linea-sepolia.address]
# admin = "0xccc435AaBc481D4Af9da51E51Eb2a383Bce6791F"
