# # 1. Ethereum
# 
# [mainnet]
# endpoint_url = "mainnet-rpc-url"
# 
# [mainnet.address]
# ctm = ""
# admin = ""
# c3governor = ""
# dist = ""
# 
# [mainnet.string]
# targetChainID = ""
# 
# [mainnet.uint]
# initialMint = ""

# 2. Sepolia
[sepolia]
endpoint_url = "sepolia-rpc-url"

[sepolia.address]
ctm = ""
admin = "0xccc435AaBc481D4Af9da51E51Eb2a383Bce6791F"
c3governor = ""

[sepolia.string]
dist = ""
targetChainID = "59141"

[sepolia.uint]
initialMint = "20148947499999000000000000" # 20_148_947 M CTM
